Hexagon Aerial Imagery blocks
up42/docs pull request #143
Opened 2019-12-11 10:54 UTC by rodrigoalmeida94

Pull Request
============

> Tracked in JIRA by [UP-3388](https://geoinformationstore.atlassian.net/browse/UP-3388)

### Scope of the PR

Add docs for Hexagon Aerial Imagery 15 and 30cm blocks.

### Checklist

- [x] Add max area for query
- [x] Checked spelling and grammar
- [x] Provided code samples where relevant
- [x] Add relevant changes to [changelog](./source/changelog.rst)
- [x] Checked the output of `make html` to ensure new content displays correctly

2020-09-22 12:43 UTC, rodrigoalmeida94 commented on source/up42-blocks/data/hexagon-aerial-15cm.rst
> +`Link <https://marketplace.up42.com/block/045019bb-06fc-4fa1-b703-318725b4d8af>`_ to block details page
@perusio @nb-42 not sure what this link should be?

2020-09-23 10:05 UTC, perusio requested changes
Please see comments below. Thank you.

2020-09-23 10:05 UTC, perusio commented on source/changelog.rst
> +.. meta::
Please do not commit the changelog. This is quite an old PR, please be mindful of re-introducing cruft. Thank you.

2020-09-23 10:05 UTC, perusio commented on source/up42-blocks/data/hexagon-aerial-15cm.rst
> +`Link <https://marketplace.up42.com/block/045019bb-06fc-4fa1-b703-318725b4d8af>`_ to block details page
Is up to @nb-42 to create the entry in the marketplace, then we can have the proper link.

2020-09-23 10:05 UTC, perusio commented on source/up42-blocks/data/hexagon-aerial-30cm.rst
> +
Can we use superscripts here: 
```
100 km :superscript:`2`
```

2020-09-23 10:05 UTC, perusio commented on source/up42-blocks/data/hexagon-aerial-15cm.rst
> +
Ditto from below:
```
25 km :superscript: `2`
```

2020-09-23 14:00 UTC, rodrigoalmeida94 commented on source/changelog.rst
> +.. meta::
Sorry, must have slipped in the rebase! Thanks

2020-09-23 15:38 UTC, perusio approved these changes
LGTM.

2020-09-24 09:24 UTC, merged