Add meteomatics weather map docs.
up42/docs pull request #224
Opened 2020-09-03 14:07 UTC by nekhtiari

Pull Request
============

> Tracked in JIRA by [IN-XXX](https://geoinformationstore.atlassian.net/browse/IN-XXX)
> Paired with @a, @b

### Scope of the PR

Describe the scope of this pull request. Is this a new feature or a bug fix?

### Checklist

- [ ] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [ ] Checked the output of `make html` to ensure new content displays correctly

2020-09-04 09:20 UTC, markusuwe reviewed
LGTM

2020-09-04 09:20 UTC, markusuwe commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +For more information, please read the ...
Read the what?

2020-09-04 09:20 UTC, markusuwe commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +* ``intersects``: A GeoJSON geometry to use as an AOI. Will return all scenes that intersect with this geometry. Use only ``bbox``
So, is contains supported or not?

2020-09-04 09:20 UTC, markusuwe commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  In this block you can choose ``pixel_resolution`` to be a number from 2
Nice!

2020-09-04 09:30 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +For more information, please read the ...
Yes, this what I put as a cm in my PR, I will add this later

2020-09-04 09:31 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +* ``intersects``: A GeoJSON geometry to use as an AOI. Will return all scenes that intersect with this geometry. Use only ``bbox``
Oh, good catch, I need to remove contain

2020-09-04 09:31 UTC, markusuwe commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +For more information, please read the ...
Oh right, should have read more carefully.

2020-09-07 05:46 UTC, thaisbendixen42 commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +   :description: UP42 data blocks: Weathet/Ocean data forecasts block
WeatheR

2020-09-07 05:53 UTC, thaisbendixen42 commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +In this example, we used the ``time_series`` parameter and selected two specific time. The variable  ``prob_precip_1h:p`` was also added. In this example we query for each date range in 3 hour interv
"[...] and selected two specific time ranges. [...]"

2020-09-07 07:12 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +   :description: UP42 data blocks: Weathet/Ocean data forecasts block
Good catch!

2020-09-08 12:27 UTC, rodrigoalmeida94 approved these changes
Nice! Just one suggestion

2020-09-08 12:27 UTC, rodrigoalmeida94 commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  for checking the other possible ``colormap_style`` you can check the `Meteomatics website
Suggestion: The possible ``colormap_style`` options can be found in the `Meteomatics website`...

2020-09-08 15:13 UTC, perusio requested changes
See below for comments. Thanks.

2020-09-08 15:13 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +================================
Make sure the underline to mark the header runs the full length of the title.

2020-09-08 15:13 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  is_slippery_road_3h:idx (also for 6h and 12h), power_line_oscillation_24h:idx, weather_code_1h:idx (also for 3, 6, 12, 24h),
Can we put this into an itemized list please?

2020-09-08 15:13 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +In this example, we used the ``time_series`` parameter and selected two specific time ranges. The variable  ``prob_precip_1h:p`` was also added. In this example we query for each date range in 3 hour
GeoTIFF.

2020-09-08 15:13 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +* ``colormap_style``: A single color scheme which should be used to represent the data. By default, ``colormap_style`` is set to JET.
Can you please provide a list of possible values or a link to where the possible values are described for `colormap_style`?

2020-09-08 15:18 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  is_slippery_road_3h:idx (also for 6h and 12h), power_line_oscillation_24h:idx, weather_code_1h:idx (also for 3, 6, 12, 24h),
Sure, I was lazy to do it to be honest :D But now that you require it, I will do!

2020-09-08 15:18 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +* ``colormap_style``: A single color scheme which should be used to represent the data. By default, ``colormap_style`` is set to JET.
I added the link for possible color_style in the `tip` part.

2020-09-08 15:19 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +================================
Will do

2020-09-08 15:20 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +In this example, we used the ``time_series`` parameter and selected two specific time ranges. The variable  ``prob_precip_1h:p`` was also added. In this example we query for each date range in 3 hour
Added!

2020-09-08 15:38 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +* ``colormap_style``: A single color scheme which should be used to represent the data. By default, ``colormap_style`` is set to JET.
My bad 🙀

2020-09-08 15:38 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  is_slippery_road_3h:idx (also for 6h and 12h), power_line_oscillation_24h:idx, weather_code_1h:idx (also for 3, 6, 12, 24h),
💪

2020-09-09 10:41 UTC, nekhtiari commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  is_slippery_road_3h:idx (also for 6h and 12h), power_line_oscillation_24h:idx, weather_code_1h:idx (also for 3, 6, 12, 24h),
I added the table @perusio, please have a look and let me know if it is good.

2020-09-09 15:25 UTC, perusio reviewed
Nice. A table is always nice, although quite tricky to do in ReST. Thanks @nekhtiari 😸

2020-09-09 15:26 UTC, perusio commented on source/up42-blocks/data/meteomatics-weather-map.rst
> +  is_slippery_road_3h:idx (also for 6h and 12h), power_line_oscillation_24h:idx, weather_code_1h:idx (also for 3, 6, 12, 24h),
Thanks

2020-09-09 15:26 UTC, perusio approved these changes
LGTM.

2020-12-16 09:47 UTC, merged