Clarify kmeans nodata
up42/docs pull request #229
Opened 2020-09-17 10:51 UTC by markusuwe

Pull Request
============

### Scope of the PR

Clarify nodata handling in kmeans block after update to be rolled out soon and fix some minor issues.

### Checklist

- [x] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [x] Checked the output of `make html` to ensure new content displays correctly

2020-09-17 11:04 UTC, chrieke reviewed
LGTM, thanks for the fixes.

2020-09-17 11:04 UTC, chrieke commented on source/up42-blocks/processing/kmeans-clustering.rst
> +- K-Means clustering. It will create a set number of clusters in each dataset and classify each pixel in one of them.
```suggestion
- K-Means clustering. It will create a set number of clusters in each dataset and classify each pixel into one of them.
```

2020-09-17 11:05 UTC, teoEnache approved these changes
Looks good

2020-09-17 11:30 UTC, perusio requested changes
This is not to appear in any index. There is a reason why it has a nofollow tag for bots. We do not advertise this feature.

2020-09-17 12:13 UTC, markusuwe commented
> This is not to appear in any index. There is a reason why it has a nofollow tag for bots. We do not advertise this feature.

Shouldn't it be removed then? The repo is open source, people can find the information even if not indexed.

2020-09-17 13:27 UTC, markusuwe commented
> > This is not to appear in any index. There is a reason why it has a nofollow tag for bots. We do not advertise this feature.
> 
> Shouldn't it be removed then? The repo is open source, people can find the information even if not indexed.

In any case, I reverted the change @perusio

2020-09-18 06:28 UTC, markusuwe commented on source/up42-blocks/processing/kmeans-clustering.rst
> +- K-Means clustering. It will create a set number of clusters in each dataset and classify each pixel in one of them.
Thanks.

2020-09-18 11:51 UTC, perusio reviewed
> > This is not to appear in any index. There is a reason why it has a nofollow tag for bots. We do not advertise this feature.
> 
> Shouldn't it be removed then? The repo is open source, people can find the information even if not indexed.

Sure they can find it. but is not easy to find it. The main thing is not being indexed anywhere. I'm wary of just having it on my machine. Better to have it replicated somewhere.

2020-09-18 11:52 UTC, perusio approved these changes
LGTM.

2020-09-18 11:56 UTC, markusuwe commented on source/up42-blocks/processing/export-data-vector.rst
> +    {
Why is that important? It looks perfectly fine in the output.

2020-09-18 11:57 UTC, markusuwe commented on source/up42-blocks/processing/kmeans-clustering.rst
> +- K-Means clustering. It will create a set number of clusters in each dataset and classify each pixel in one of them.
Fixed.

2020-09-18 12:01 UTC, markusuwe commented on source/up42-blocks/processing/kmeans-clustering.rst
> +from all other pixels (measured by the Frobenius or L2 norm), all nodata pixels will likely form a separate cluster.
Added a link to wikipedia

2020-09-18 12:08 UTC, markusuwe commented on source/up42-blocks/processing/export-data-vector.rst
> +    {
Just checked in my code, these actually are blanks.

2020-09-18 12:09 UTC, merged