Add ndvithresholding
up42/docs pull request #235
Opened 2020-10-16 11:05 UTC by nekhtiari

Pull Request
============

> Tracked in JIRA by [IN-XXX](https://geoinformationstore.atlassian.net/browse/IN-XXX)
> Paired with @a, @b

### Scope of the PR

Add documentation for NDVI thresholding.

### Checklist

- [ ] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [ ] Checked the output of `make html` to ensure new content displays correctly

2020-10-16 11:20 UTC, perusio requested changes
There seems to be some copy& paste error where the example values are for another block. As you know we have a customer on the queue for this and we want to push to him ASAP but with good documentation. I'm here to help you @nekhtiari together with @teoEnache so that we get the customer to easily use the block.

Thank you.

2020-10-16 11:20 UTC, perusio commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +Example using ``n_sieve_pixels`` and ``threshold_values``:
where are the values for this blocks params? This seems to be about the OA basemap. No? 🤔

2020-10-16 11:22 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +Example using ``n_sieve_pixels`` and ``threshold_values``:
No Antonio, it is for ndvithresholding block that I am currently working, the reason that I made this PR as a Draft was simply because it is still incomplete. I just wanted to have it here so when I finished my implementation little work remains for me.

2020-10-19 15:18 UTC, rodrigoalmeida94 approved these changes
LGTM!

2020-10-20 05:46 UTC, markusuwe requested changes
Minor things, but important is the slightly misleading section about the input block.

2020-10-20 05:46 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +For more information, please read the ...
Guess this needs to be updated?

2020-10-20 05:46 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +This block applies thresholding for NDVI values. This block is mainly suitable to be used with `Pleiades Download block <https://docs.up42.com/up42-blocks/data/pleiades-download.html>`_
This section is misleading. The input needs to be NDVI and does not depend too much on the underlying dataset used to create it.
Also: we initially discussed that this block does not only support our NDVI block, but also those implemented by partners. Was this plan cancelled?

2020-10-20 05:46 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +* ``threshold_values``: A list of a dictionary with specific land type and corresponding threshold values.
I assume this is just a dictionary and not a list of dictionaries?

2020-10-20 05:46 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +===================================
Please adjust length. If you run make_html this likely produces a warning.

2020-10-20 05:46 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +Land types and values for thresholding
Maybe better vegetation types?

2020-10-20 05:46 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +Below is the default threshold values that is been set for the block. However, you can change ``threshold_values`` based on your
```suggestion
Below are the default threshold values that were set for the block. However, you can change ``threshold_values`` based on your
```

2020-10-20 05:47 UTC, markusuwe commented
> # Pull Request
> > Tracked in JIRA by [IN-XXX](https://geoinformationstore.atlassian.net/browse/IN-XXX)
> > Paired with @A, @b
> 
> ### Scope of the PR
> Add documentation for NDVI thresholding.
> 
> ### Checklist
> * [ ]  Checked spelling and grammar
> * [ ]  Provided code samples where relevant
> * [ ]  Checked the output of `make html` to ensure new content displays correctly

Can you please check the checklist?

2020-10-20 06:53 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +* ``threshold_values``: A list of a dictionary with specific land type and corresponding threshold values.
It is indeed a dict, but having only a dict as a parameter is not supported in specification (https://github.com/up42/specifications/blob/master/v2/blocks/parameters-schema.json), so I had to come up with a workaround and therefore I put it in a list. I can ignore mentioning here! I just want to be exact.

2020-10-20 06:56 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +This block applies thresholding for NDVI values. This block is mainly suitable to be used with `Pleiades Download block <https://docs.up42.com/up42-blocks/data/pleiades-download.html>`_
Right, I was just thinking if I only mention ndvi block before, a user would ignore the stuff that needs to be added before. Also, I mentioned the word "mainly" so I guess it is saying that it is not only working with our ndvi. I will add a sentence to be precise here.

2020-10-20 06:57 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +For more information, please read the ...
I think this is always your favorite part of cm on docs! yes, it will be!

2020-10-20 07:00 UTC, markusuwe commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +* ``threshold_values``: A list of a dictionary with specific land type and corresponding threshold values.
Exact is good, having a list of dicts is not that great, but not a topic for docu review (but for the code). Seems I missed that one, so from the docu side go ahead.

2020-10-20 07:47 UTC, thaisbendixen42 commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +Below are the default threshold values that were been set for the block. However, you can change ``threshold_values`` based on your
[...] values that **have** been set for the block [...]

2020-10-20 07:58 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +Below are the default threshold values that were been set for the block. However, you can change ``threshold_values`` based on your
Thank you :D my english is problematic here

2020-10-20 08:58 UTC, markusuwe approved these changes
LGTM

2020-10-21 14:46 UTC, perusio requested changes
Please see below.

2020-10-21 14:46 UTC, perusio commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +However, other blocks on the marketplace that provide ndvi values can also be used with this block.
NDVI (is an acronym)

2020-10-21 14:46 UTC, perusio commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +NDVI Threshold
Isn't it a bit _funny_ that the page title and the filename are not aligned? Shouldn't it be: **NDVI Thresholding**. Also is an **action** not an object.

2020-10-21 14:46 UTC, perusio commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +* ``n_sieve_pixels``: Number of the connected pixels (small polygon) that will be replaced in output with value of their largest neighbor.
in the output.

2020-10-21 14:46 UTC, perusio commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +   +-----------------------------+---------------------------------+
You can only have **4** classes and the only degree of freedom is on the range for each?

2020-10-22 08:18 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +However, other blocks on the marketplace that provide ndvi values can also be used with this block.
Ok, will fix it.

2020-10-22 08:21 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +NDVI Threshold
Right, but now block has been published with `NDVI Threshold` title. I can change the filename here to be consistent.

2020-10-22 08:21 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +* ``n_sieve_pixels``: Number of the connected pixels (small polygon) that will be replaced in output with value of their largest neighbor.
Good catch

2020-10-22 08:22 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +   +-----------------------------+---------------------------------+
No people can add more classes if they want. The code will handle this dictionary in a generic way.

2020-10-22 08:37 UTC, nekhtiari commented on source/up42-blocks/processing/up42-ndvithresholding.rst
> +   +-----------------------------+---------------------------------+
I added also vegetation types to make it more clear that people can add more classes

2020-10-26 12:52 UTC, perusio approved these changes
LGTM

2020-10-26 12:53 UTC, merged