Oa display documentation
up42/docs pull request #241
Opened 2020-11-11 15:52 UTC by thaisbendixen

Pull Request
============

> Tracked in JIRA by 

### Scope of the PR

Documentation for OneAtlas Pleiades and SPOT Display products.

### Checklist

- [ ] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [ ] Checked the output of `make html` to ensure new content displays correctly

2020-11-12 07:47 UTC, teoEnache approved these changes
LGTM

2020-11-13 14:39 UTC, perusio requested changes
Please see below. Can we add something also about DIMAP -> GeoTIFF conversion? 🤔
Obrigado.

2020-11-13 14:39 UTC, perusio commented on source/up42-blocks/data/pleiades-display.rst
> +The available output bands of the Pleiades block are: red, green, blue and near infrared. Pansharpened Pléiades HR imagery has a spatial resolution of 0.5x0.5m. The multispectral bands have a resolut
This block delivers pansharpened imagery also AFAIK. So maybe rephrase it along those lines.

2020-11-13 14:39 UTC, perusio commented on source/up42-blocks/data/spot-display.rst
> +The available output bands of the SPOT block are: red, green, blue and near infrared. SPOT Pansharpened imagery has a spatial resolution of 2x2m. The multispectral bands have a resolution of 8x8m.
Ditto.

2020-11-16 07:46 UTC, teoEnache approved these changes
LGTM

2020-11-18 11:22 UTC, perusio reviewed
I will change the GeoTiff to GeoTIFF here and merge it.

2020-11-18 11:22 UTC, perusio commented on source/up42-blocks/data/pleiades-display.rst
>     Find out more about the DIMAP image format `here <https://www.intelligence-airbusds.com/en/8722-the-dimap-format>`_. DIMAP is a GDAL supported `raster format <https://gdal.org/drivers/raster/dimap
GeoTIFF.

2020-11-18 11:22 UTC, perusio commented on source/up42-blocks/data/spot-display.rst
> +    The DIMAP format may be converted into GeoTiff format using the `DIMAP -> GeoTIFF conversion block <https://marketplace.up42.com/block/c94bb4cd-8ee2-40df-ba76-d332b8f48c6a>`_.
GeoTIFF.

2020-11-18 11:27 UTC, merged