add ee-ais-query-vessel
up42/docs pull request #253
Opened 2020-12-04 14:25 UTC by chrieke

Pull Request
============

### Scope of the PR

Add exactearth-ais-query-vessel, [block](https://marketplace.up42.com/block/75598899-26bf-4d1a-9a1c-b9d59bf0549a).

### Checklist

- [x] Checked spelling and grammar
- [x] Provided code samples where relevant
- [x] Checked the output of `make html` to ensure new content displays correctly

2020-12-04 14:32 UTC, teoEnache approved these changes
great!

2020-12-04 15:01 UTC, perusio requested changes
See below. Minor issues. Thx.

2020-12-04 15:01 UTC, perusio commented on source/up42-blocks/data/exactearth-ais-query-vessel.rst
> +
Can we indent this code in a nicer way, e.g., using `jq` or jsonlint.com? Is somewhat hard to read.

2020-12-05 14:45 UTC, chrieke commented on source/up42-blocks/data/exactearth-ais-query-vessel.rst
> +* ``mmsi``: Ids of Maritime Mobile Service Identity (MMSI), e.g. ``["83273282", "94821299"]``.
added mmsi link, no public source for eeid unfortunately, only in login api docs.

2020-12-05 14:46 UTC, chrieke commented on source/up42-blocks/data/exactearth-ais-query-vessel.rst
> +
formatted, also for other ais blocks.

2020-12-11 14:43 UTC, perusio approved these changes
LGTM

2020-12-11 14:44 UTC, merged