Add import geojson data first draft
up42/docs pull request #257
Opened 2020-12-16 09:52 UTC by nekhtiari

Pull Request
============

> Tracked in JIRA by [IN-XXX](https://geoinformationstore.atlassian.net/browse/IN-XXX)
> Paired with @a, @b

### Scope of the PR

Describe the scope of this pull request. Is this a new feature or a bug fix?

### Checklist

- [ ] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [ ] Checked the output of `make html` to ensure new content displays correctly

2020-12-16 16:10 UTC, teoEnache reviewed
please update the block description with the one from prod, not staging (<https://marketplace.up42.dev/block/1540a0f2-a6d5-4262-944f-21117ad658be>)

2020-12-16 16:13 UTC, teoEnache requested changes
this page needs to be from prod: <https://marketplace.up42.dev/block/1540a0f2-a6d5-4262-944f-21117ad658be>

2020-12-17 06:29 UTC, markusuwe approved these changes
LGTM

2020-12-18 06:26 UTC, perusio requested changes
Minor language and formatting issues below.

2020-12-18 06:26 UTC, perusio commented on source/up42-blocks/data/up42-import-geojson.rst
> +This block enables using GeoJSON vector data, stored in a bucket on *Google Cloud Storage (GCS)*
Do you mean italic or bold here?

2020-12-18 06:26 UTC, perusio commented on source/up42-blocks/data/up42-import-geojson.rst
> +location and time. The search can also be limited to a subfolder in the bucket via the
location and date

2020-12-18 06:26 UTC, perusio commented on source/up42-blocks/data/up42-import-geojson.rst
> +The block outputs the scene data and an automatically created `data.json` file with the scene metadata.
is it not:
``data.json``?

2020-12-18 06:26 UTC, perusio commented on source/up42-blocks/data/up42-import-geojson.rst
> +    For AWS, provide the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as environment variables.
Ditto it requires two ``  to show up as code.

2020-12-18 08:50 UTC, nekhtiari commented on source/up42-blocks/data/up42-import-geojson.rst
> +This block enables using GeoJSON vector data, stored in a bucket on *Google Cloud Storage (GCS)*
Sorry I do not understand, with one star is italic, right? I just copy-paste it from the other two custom data blocks.

2020-12-18 08:50 UTC, nekhtiari commented on source/up42-blocks/data/up42-import-geojson.rst
> +The block outputs the scene data and an automatically created `data.json` file with the scene metadata.
oh sorry this is a leftover, will change it

2020-12-18 09:10 UTC, nekhtiari commented on source/up42-blocks/data/up42-import-geojson.rst
> +location and time. The search can also be limited to a subfolder in the bucket via the
done

2020-12-18 09:28 UTC, nekhtiari commented on source/up42-blocks/data/up42-import-geojson.rst
> +    For AWS, provide the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as environment variables.
done

2020-12-18 09:31 UTC, nekhtiari commented
> this page needs to be from prod: https://marketplace.up42.dev/block/1540a0f2-a6d5-4262-944f-21117ad658be

Updated :)

2020-12-18 09:32 UTC, perusio approved these changes
LGTM.

2020-12-18 09:34 UTC, merged