Add image statistics docs
up42/docs pull request #277
Opened 2021-02-01 14:45 UTC by nekhtiari

Pull Request
============
### Scope of the PR

This PR adds the documentation for the up42 image statistics block.

### Checklist

- [ ] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [ ] Checked the output of `make html` to ensure new content displays correctly

2021-02-01 14:46 UTC, teoEnache approved these changes
looks good

2021-02-01 16:26 UTC, perusio requested changes
It computes the mean on what? On the value of each band? Is unclear to me what it does. Can you elaborate on it please? Thank you.

2021-02-02 08:34 UTC, nekhtiari commented
> It computes the mean on what? On the value of each band? Is unclear to me what it does. Can you elaborate on it please? Thank you.

Added. Please check and if it is good so I can merge.

2021-02-02 10:54 UTC, perusio requested changes
But does apply across all bands of the source image?

2021-02-02 11:05 UTC, nekhtiari commented
> But does apply across all bands of the source image?

Here we only have images with 1 band. Mostly used for weather or climate analysis, specifically will work with our new s5 geotiff block

2021-02-03 11:38 UTC, seulgi-up42 approved these changes
Looks good to me as well! (The only small comment I have is that the images are a bit vague in the block description link you provided but I'm not sure if this is right place to bring that up).

2021-02-03 11:53 UTC, nekhtiari commented
> Looks good to me as well! (The only small comment I have is that the images are a bit vague in the block description link you provided but I'm not sure if this is right place to bring that up).

Nice to have your comment. The images will be taken care of later via Niklas. I hope that makes sense.

2021-02-05 08:04 UTC, markusuwe approved these changes
LGTM

2021-02-05 08:04 UTC, markusuwe commented on source/up42-blocks/processing/up42-image-statistics.rst
> +Image Statistics
```suggestion
UP42 Image Statistics
```

2021-02-05 08:04 UTC, markusuwe commented on source/up42-blocks/processing/up42-image-statistics.rst
> +This block applies statistics on a stack of raster inputs. The statistics can be one of the following: ``mean``, ``min``, ``max``, ``std``, ``median``, or ``sum``.
```suggestion
This block applies statistics on a stack of raster inputs and creates a raster file containing the result. The statistics can be one of the following: ``mean``, ``min``, ``max``, ``std``, ``median``, or ``sum``.
```

2021-02-05 08:04 UTC, markusuwe commented on source/up42-blocks/processing/up42-image-statistics.rst
> +For more information, please read the `block description <https://marketplace.up42.dev/block/93d73b17-6d9b-46aa-9745-15dd5d8c4be0>`_.
Is it worthwhile adding a sentence what kind of inputs can be processed?

2021-02-05 08:11 UTC, marooned20 commented on source/up42-blocks/processing/index.rst
> +   up42-image-statistics
```suggestion
   up42-timeseries-image-statistics
```

2021-02-05 08:21 UTC, nekhtiari commented on source/up42-blocks/processing/up42-image-statistics.rst
> +For more information, please read the `block description <https://marketplace.up42.dev/block/93d73b17-6d9b-46aa-9745-15dd5d8c4be0>`_.
added

2021-02-05 10:59 UTC, merged