Add worlddem docs
up42/docs pull request #286
Opened 2021-02-19 14:11 UTC by nekhtiari

Pull Request
============

### Scope of the PR

Add documentation for WorldDEM 12m data block.

### Checklist

- [ ] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [ ] Checked the output of `make html` to ensure new content displays correctly

2021-02-19 14:13 UTC, rodrigoalmeida94 approved these changes

2021-02-22 09:53 UTC, teoEnache approved these changes

2021-02-22 09:57 UTC, thaisbendixen approved these changes
LGTM!

2021-02-22 09:59 UTC, seulgi-up42 requested changes
Everything looks good to me, just one tiny change with "represents" to "represent" in the second sentence of the block description.

2021-02-22 10:50 UTC, nekhtiari commented
> Everything looks good to me, just one tiny change with "represents" to "represent" in the second sentence of the block description.

fixed, thanks for catching it.

2021-02-22 10:54 UTC, seulgi-up42 approved these changes
Looks great! Approved!

2021-02-22 13:54 UTC, markusuwe commented on source/up42-blocks/data/oneatlas-worlddem-12m.rst
> +WorldDEM Full Resolution
Latest block naming standard says we also put the provider name here, no?

2021-02-22 13:56 UTC, nekhtiari commented on source/up42-blocks/data/oneatlas-worlddem-12m.rst
> +WorldDEM Full Resolution
Oh, I did not know this. I can add OneAtlas in the beginning.

2021-03-01 08:45 UTC, merged