Remove max image size for Vectorising
up42/docs pull request #302
Opened 2021-03-05 15:14 UTC by rodrigoalmeida94

Pull Request
============

> Tracked in JIRA by [UP-5363](https://geoinformationstore.atlassian.net/browse/UP-5363)

### Scope of the PR

Removes the warning about the maximum image size given the tiled vectorising implementation in https://github.com/up42/blocks/pull/919. Block will now be able to process almost all the images being inputed.

### Checklist

- [x] Checked spelling and grammar
- [x] Provided code samples where relevant
- [x] Checked the output of `make html` to ensure new content displays correctly

2021-03-05 17:15 UTC, perusio requested changes
Minor linking thing pointed below. Thank you.

2021-03-05 17:15 UTC, perusio commented on source/up42-blocks/processing/vectorization.rst
>    is the result of a **K-Means Clustering** or a **Land Cover Classification**.
Or of NDVI Threshold. Also we can add links to block pages, i.e., K-means, Land Cover, etc.

2021-03-12 13:53 UTC, markusuwe approved these changes
LGTM

2021-03-12 16:10 UTC, perusio approved these changes
LGTM

2021-03-12 16:11 UTC, merged